[supervisord]
nodaemon=true
user=root
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:reverb]
process_name=%(program_name)s
directory=/var/www
command=docker-php-entrypoint php artisan reverb:start --host=0.0.0.0 --port=8080
autostart=true
autorestart=true
user=www-data
stopwaitsecs=10
stdout_logfile=/var/www/storage/logs/reverb.log
stderr_logfile=/var/www/storage/logs/reverb.err.log
